-- AlterTable
ALTER TABLE "configuracion_tienda" ADD COLUMN     "checkoutActivo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutBotonFijo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutBotonTexto" TEXT NOT NULL DEFAULT 'REALIZAR PEDIDO',
ADD COLUMN     "checkoutCantidadMaxima" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "checkoutCiudadObligatoria" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutDireccionObligatoria" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutDniObligatorio" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "checkoutMensajeExito" TEXT NOT NULL DEFAULT 'Tu pedido fue registrado correctamente.',
ADD COLUMN     "checkoutMostrarCiudad" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutMostrarDireccion" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutMostrarDni" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "checkoutMostrarReferencia" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutMostrarRegion" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutMostrarTotal" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutPermitirCantidad" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutReferenciaObligatoria" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "checkoutRegionObligatoria" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "checkoutTextoConfianza" TEXT NOT NULL DEFAULT 'Compra segura | Envíos a todo el Perú',
ADD COLUMN     "checkoutTipoPedido" TEXT NOT NULL DEFAULT 'CONTRAENTREGA',
ADD COLUMN     "checkoutTitulo" TEXT NOT NULL DEFAULT 'Completa tus datos para realizar tu pedido',
ADD COLUMN     "checkoutWhatsAppPostPedido" BOOLEAN NOT NULL DEFAULT false;
